# Generated by Django 2.2.2 on 2019-08-19 16:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_auto_20190819_1540'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Tutorial',
            new_name='Product',
        ),
        migrations.RenameField(
            model_name='product',
            old_name='tutorial_content',
            new_name='product_content',
        ),
        migrations.RenameField(
            model_name='product',
            old_name='tutorial_published',
            new_name='product_published',
        ),
        migrations.RenameField(
            model_name='product',
            old_name='tutorial_title',
            new_name='product_title',
        ),
    ]
